phraseapp:
  access_token: 09fed8fe0882a8d04ec0815c8d8e472d671b535434c36a60c7d9adfcfd9338ae
  project_id: 6b37be3bd8f37ca54f479949fc8888f1
  file_format: yml
  push:
    sources:
    - file: ./config/locales/<tag>.<locale_name>.yml
      params:
        file_format: yml
  pull:
    targets:
    - file: ./config/locales/<tag>.<locale_name>.yml
      params:
        file_format: yml
