# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ddce0e85a784658a21b6e14369949ebe6ab0b8f9b90ed6e42ca7527c948ca139ed6c08a7041a0dd296a5293bb5dfbf16db28570d819ba0714774d6f37a35f7f

test:
  secret_key_base: 337ceaec1a9eadffa4f75e7423fde6ee9dc10ec928e944578628bae9bfa7205d03e5d47c3616c915c08a5c2d40f0a29014c347e1299366518e650d858d7e6cb5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
